version: "3.8"
services:
  postgres_dev:
    container_name: chady_dev
    image: postgres:14-alpine
    ports:
      - 2020:5432
    volumes:
      - /var/lib/chady:/data/
    environment:
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_USER=dev_user
      - POSTGRES_DB=chady_db
